### ISSUE TITLE
How did you get ftp endpoint?

### ISSUE THREAD

**Issue by romulojales** [crishoj/odf-fetch#1]
I'm really curious to know How did you get the ftp endpoint, user and pass? 
Is this information public?

**Comment by crishoj** [comment]
Access credentials were provided by the contractor responsible for data feeds (www.atos.net during the 2014 games). I doubt credentials are public, but reaching out to the data feeds contractor might be worth a try.

**Comment by romulojales** [comment]
Thank you very much!
